[api]
enabled = true
port = 54321
schemas = ["public"]

[db.migrations]
enabled = true

[db.seed]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lifelinemesh.com/*"]
jwt_expiry = 3600
enable_signup = true

[auth.sms.twilio]

[edge_runtime]
enabled = true
policy = "per_worker"



[storage]
enabled = true
file_size_limit = "50MB"

[realtime]
enabled = true

[analytics]
enabled = true

[experimental]
orioledb_version = "1"