[api]
enabled = true
port = 54321
schemas = ["public"]

[db.migrations]
enabled = true

[db.seed]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lifelinemesh.com/*"]
jwt_expiry = 3600
enable_signup = true

[auth.sms.twilio]

[edge_runtime]
enabled = true
policy = "per_worker"



[storage]
enabled = true
file_size_limit = "50MB"

[realtime]
enabled = true

[analytics]
enabled = true

[experimental]
orioledb_version = "1"
[functions.verify-identity]
enabled = true
verify_jwt = false
import_map = "./functions/verify-identity/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-identity/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-identity/*.html" ]
